version: "2.1"

services:
  devagent:
    build:
      context: .
    restart: always
    privileged: true
    ports:
      - "1880:1880"
    volumes:
      - ff-device:/opt/flowfuse-device

volumes:
  ff-device:
