version: "2.1"
networks: {}
volumes:
  resin-data: {}
services:
  devagent:
    build:
      context: .
    restart: always
    privileged: true
    ports:
      - "1880:1880"
    volumes:
      - resin-data:/opt/flowfuse-device
